export * from './SignUp/SignUp';
export * from './SingIn/SignIn';
export * from './Main/Main';
export * from './Info1/Info1';
export * from './Message/Message';
export * from './ProFile/Profile';
export * from './MyWork/MyWork';
export * from './Jobs/Jobs';
export * from './Loading/Loading';